### ISSUE TITLE
LICENSE of binGraph

### ISSUE THREAD

**Issue by adulau** [geekscrapy/binGraph#6]
binGraph is really nifty and I would like to integrate it as a [misp-modules](https://github.com/MISP/misp-modules). I cannot find the license file. What's the open source license of binGraph? Thank you very much.

**Comment by geekscrapy** [comment]
Hi @adulau, thanks! I was actually prepping it for use as a Cortex module too. There is currently a pull request to make it usable as a library so once that is merged it will probably be the best point to add as a misp-module and also Cortex.

In terms of license, I hadn't actually decided yet, but I want it to be open, like misp. I also need it compatible with Cuckoo so need to do a review

Thanks

**Comment by adulau** [comment]
Thanks for the quick feedback. FYI, a 3-clause license would work for Cuckoo, Cortex/TheHive and MISP.

**Comment by geekscrapy** [comment]
I have now added the license.

FYI I'm about to review the pull request for making it into a library

**Comment by geekscrapy** [comment]
Hi @adulau I think it can be used within a misp-module now :) If I get time I'll have a look at it, but it's not looking like it's going to be anytime soon!

**Comment by adulau** [comment]
Thanks for the license change. I'll have a look if we could a misp-module soon. Thanks a lot.
